[project]
name = "leadprofile"
version = "0.1.0"
dependencies = [
    "crewai>=0.114.0",
    "crewai-tools>=0.40.1",
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.3",
    "pydantic>=2.11.3",
]
[tool.setuptools.packages.find]
where = ["leadprofile/src"]
