# leadprofile/config/tasks.yaml
ddd_task:
  description: >
    Extraia o DDD do número {phone}. Em seguida, consulte o blog da Claro
    para obter:

    • Estado
    • Lista completa de cidades atendidas

    Use a ferramenta **ddd_scraper**.  
    Retorne um JSON válido com as chaves:
    - state: string
    - cities: lista de strings
    - url: string (link da página raspada)
  expected_output: >
    JSON válido com "state", "cities" e "url".
  agent: location_identifier
